---
- name: Install default Apache Web Server
  hosts: target4
  become: yes
#  become_user: root
#  become_method: sudo
  tasks:

  - name: Install Apache WebServer
    apt:
      name: apache2
      state: present
      update_cache: yes

  - name: Start Apache and Enable it on the every boot
    service: name=apache2 state=started enabled=yes


# instaliruet webserver Apache na host i zapuskaet ego i perezapuskaet
# ansible-playbook playbook2-install-Apache.yml -b -k -K 
